name: Build Android APK

on:
  push:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Gradle (Version 9.3.1)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.3.1'

      - name: Créer le fichier debug.keystore manquant 🔑
        run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

      - name: Compilation de l'APK via Gradle
        run: gradle assembleDebug --stacktrace

      - name: Télécharger l'APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: '**/build/outputs/apk/debug/*.apk'
